### ISSUE TITLE
ModuleNotFoundError: No module named 'bitorch.datasets\\base'

### ISSUE THREAD

**Issue by BenoitDalFerro** [hpi-xnor/bitorch#1]
**Bug description**

Fails to import bitorch modules (copied as per notebook tutorial)

```
from bitorch.layers import (
    QLinear,
    QActivation,
    #QConv2d_NoAct,
    WeightGraphicalDebug
)
```

same behaviour by the way with sanity check

`from bitorch import (QLinear)`

nor

`import bitorch`

result as follow

> Traceback (most recent call last):
>    File "test.py", line 44, in <module>
>      from mymodule import (myfunction,
>    File "...\test.py", line 24, in <module>
>      from bitorch.layers import (
>    File "mycondadir\lib\site-packages\bitorch\__init__.py", line 21, in <module>
>      module = import_module(import_path)
>    File "mycondadir\lib\importlib\__init__.py", line 127, in import_module
>      return _bootstrap._gcd_import(name[level:], package, level)
>  ModuleNotFoundError: No module named 'bitorch.datasets\\base'

**Config**

> PyTorch version: 1.11.0
> Is debug build: False
> CUDA used to build PyTorch: 11.3
> ROCM used to build PyTorch: N/A
> 
> OS: Microsoft Windows 10 Professionnel
> GCC version: Could not collect
> Clang version: Could not collect
> CMake version: Could not collect
> 
> Python version: 3.8 (64-bit runtime)
> Is CUDA available: True
> CUDA runtime version: 11.5.119
> GPU models and configuration: GPU 0: Quadro RTX 3000
> Nvidia driver version: 472.98
> cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin\cudnn_ops_train64_8.dll
> HIP runtime version: N/A
> MIOpen runtime version: N/A
> 
> Versions of relevant libraries:
> [pip3] bitorch==0.1.1
> [pip3] bitorchinfo==0.1.0
> [pip3] numpy==1.21.5
> [pip3] pytorch-lightning==1.5.10
> [pip3] torch==1.11.0
> [pip3] torchaudio==0.11.0
> [pip3] torchinfo==1.6.3
> [pip3] torchmetrics==0.7.2
> [pip3] torchvision==0.12.0
> [pip3] torchviz==0.0.2
> [conda] bitorch                   0.1.1                    pypi_0    pypi
> [conda] bitorchinfo               0.1.0                    pypi_0    pypi
> [conda] blas                      1.0                         mkl
> [conda] cudatoolkit               11.3.1               h59b6b97_2
> [conda] mkl                       2021.4.0           haa95532_640
> [conda] mkl-service               2.4.0            py38h2bbff1b_0
> [conda] mkl_fft                   1.3.1            py38h277e83a_0
> [conda] mkl_random                1.2.2            py38hf11a4ad_0
> [conda] numpy                     1.21.5           py38ha4e8547_0
> [conda] numpy-base                1.21.5           py38hc2deb75_0
> [conda] pytorch                   1.11.0          py3.8_cuda11.3_cudnn8_0    pytorch
> [conda] pytorch-lightning         1.5.10             pyhd8ed1ab_0    conda-forge
> [conda] pytorch-mutex             1.0                        cuda    pytorch
> [conda] torchaudio                0.11.0               py38_cu113    pytorch
> [conda] torchinfo                 1.6.3              pyhd8ed1ab_0    conda-forge
> [conda] torchmetrics              0.7.2              pyhd8ed1ab_0    conda-forge
> [conda] torchvision               0.12.0               py38_cu113    pytorch
> [conda] torchviz                  0.0.2                    pypi_0    pypi

**Comment by Snagnar** [comment]
Thank you for opening an issue! The bug reported should now be fixed (though with a different implementation than provided in your pull request). Could you check if the bug still persists with the new release of bitorch?
